name: Build, push to DockerHub and deploy to DigitalOcean Droplet

on:
  push:
    tags:
      # Production release, ex: v1.0.0
      - v\d+\.\d+\.\d+
      # Staging release, ex: v1.0.0-alpha.1
      - v\d+\.\d+\.\d+\-alpha.\d+

jobs:
  setup-build-push-deploy:
    name: Setup, Build, Push, and Deploy
    runs-on: ubuntu-latest
  
    steps:
      # CHECKING OUT CURRENT SRC CODE VERSION, A MUST!
      - name: Checkout
        uses: actions/checkout@v2
      
      # CONFIGURING DOCKER
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_ACCESS_TOKEN }}
      
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v1
      
      # Build the Docker image
      - name: Build
        run: |-
          make build

      # Push the Docker image to Google Container Registry
      - name: Push
        run: |-
          make push